# Generated by Django 5.0.4 on 2024-05-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_customer_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Contactno',
            new_name='contactno',
        ),
    ]
